services:
  - type: web
    name: it0049-pos
    runtime: docker
    buildCommand: "composer install"
    startCommand: "php -S 0.0.0.0:$PORT -t public"
    envVars:
      - key: CI_ENVIRONMENT
        value: production